### ISSUE TITLE
Slowmode command accepts non integers

### ISSUE THREAD

**Issue by ghost** [Cache-Bot/Issues#4]
The slowmode command accepts non integers as an argument and returns an error. For the issue, I used !slowmode h and it return a Discord API error:

Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In rate_limit_per_user: Value "h" is not int.

**Comment by wotanut** [comment]
Will look into it ASAP and hopefully should have a patch ready within a week or so, will update when I have time.

**Comment by wotanut** [comment]
Fixed as of v1.5.1

Thanks for reporting!
