### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Immortal-3527** [Cache-Bot/Issues#8]
change this category to one channel because they all say pretty much the same thing
![image](https://user-images.githubusercontent.com/63643867/128614844-6c58af50-b8d6-4463-9381-4777042066e0.png)

**Comment by wotanut** [comment]
I'm kind of torn on this

On the one hand I feel like they all need seperate channels

On the other hand I feel like they're all the same thing and I can use the other two for different channels like status-checker-support.

I'll ask the community tommorow!

**Comment by LuisPavelA** [comment]
We could just delete the category and its channels because it already says the link to the issues page in #welcome 
![image](https://user-images.githubusercontent.com/73752198/128616921-ccf3019d-46a5-4683-8984-41dfab594c14.png)

**Comment by wotanut** [comment]
When asked in the server the community had a mixed response, about 25% agreed and about 25% disagreed

50% of people did not care, so for the time being these channels will remain as they are.
